[package]
name = "myps"
version = "0.1.0"
edition = "2018"

[dependencies]
util = { path = "../util" }
pest = "*"
pest_derive = "*"
lazy_static = "*"
petgraph = "*"
itertools = "*"
serde = "1.0.114"
ron = "0.6.0"

