[workspace]
members = [
    # Libraries
    "./mips-parser",
    "./mips-simulator",
    "./util",
    "./myps",
    # Simulator tools
    "./mips-simulator/tools/mips-simulator-cli",
    "./mips-simulator/tools/stationeering-to-ron"
]
