[package]
name = "mips-parser"
version = "0.1.0"
edition = "2018"

[lib]
name = "mips_parser"
path = "src/lib.rs"

[[bin]]
name = "parser_test"
path = "src/main.rs"

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
itertools = "0.9.0"

