[package]
name = "mips-state"
version = "0.1.0"
edition = "2018"

[lib]
name = "mips_state"
path = "src/lib.rs"

[[bin]]
name = "mips_state_test"
path = "src/main.rs"

[dependencies]
mips-parser = { path = "../mips-parser" }
util = { path = "../util" }
#thiserror = "1.0.20"

